THEME_SIZE = 300
EMAIL_SIZE = 100  # is anybody needs more?

TICKET_STATUS_OPENED = 0
TICKET_STATUS_CLOSED = 1
TICKET_STATUS_PENDING = 2
TICKET_STATUS_RESOLVED = 3

AVAILABLE_STATUSES = (TICKET_STATUS_OPENED, TICKET_STATUS_CLOSED, TICKET_STATUS_PENDING, TICKET_STATUS_RESOLVED)

STATUS_NAMES = {
    TICKET_STATUS_OPENED: 'opened',
    TICKET_STATUS_CLOSED: 'closed',
    TICKET_STATUS_PENDING: 'pending',
    TICKET_STATUS_RESOLVED: 'resolved'
}

ALLOWED_TRANSITIONS = {
    TICKET_STATUS_OPENED: (TICKET_STATUS_PENDING, TICKET_STATUS_CLOSED),
    TICKET_STATUS_PENDING: (TICKET_STATUS_RESOLVED, TICKET_STATUS_CLOSED),
    TICKET_STATUS_RESOLVED: (TICKET_STATUS_PENDING, TICKET_STATUS_CLOSED)
}